### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by gajus** [gajus/seeql#7]
It would be nice to have a logo for the project.

"SeeQL" is about being able to see the queries. Therefore, an eye, glasses, ... + SQL would do.

**Comment by theodorosploumis** [comment]
I will come back with some proposals on Monday if you like. Thanks!

**Comment by gajus** [comment]
:-)

**Comment by theodorosploumis** [comment]
Here you are. The proposals have no wording on side to avoid bad design and other issues. I prefer No 1 and then No 4 but I will not be the one to decide! Last proposals are more elegant but more difficult to print also.

![seeql_proposals_v1](https://cloud.githubusercontent.com/assets/1315321/24325250/7423a1ca-119d-11e7-8f17-3e850b4b6657.png)

**Comment by gajus** [comment]
Wow. These look great! The first 1st one is definitely my favourite.

**Comment by gajus** [comment]
I am leaving this open. I think the first one looks great. I will do some improvements to the SeeQL and try to release an upgraded version sometime next week, with attribution to the logo creator.

**Comment by theodorosploumis** [comment]
Maybe I create some proposals based on 1 (mostly with other glasses).

**Comment by theodorosploumis** [comment]
Here we are. Eye glasses with db icon.


![proposals_v1](https://cloud.githubusercontent.com/assets/1315321/24431672/15ebe8e8-1426-11e7-99a2-a45186229055.png)

**Comment by theodorosploumis** [comment]
Hi, any progress with this? :-)

**Comment by gajus** [comment]
The project has stalled as I've moved on to use Postgres instead of MySQL.

I've not got enough experience with Postgres yet to update Seeql to support the protocol. It is going to be a while.

**Comment by theodorosploumis** [comment]
In any case I was talking about the progress with the current issue - **logo selection** which will probably not affected if the db to monitor is a Postgres.

**Comment by gajus** [comment]
Oh, 1H is the best.

Sorry, didn't realize I didn't follow up on that.

**Comment by Chris2011** [comment]
Maybe a little SQL query under the left eye would be nice too or smth like that. I like the proposals :)

**Comment by Chris2011** [comment]
Found the project view minutes ago. Would be great to see this tool growing :) But this is an other topic :)
